exporter:
  # Identity
  node: 
  server: 
  # Exporter Prefix
  prefix: dsc_
  # DSC XML Path
  xmlPath: dsc
  # Transformers
  transformers:
    - ";Labler;*;yaml=labler.yaml"
    - ";ReRanger;rcode_vs_replylen;range=/64;pad_to=5"
    - ";ReRanger;qtype_vs_qnamelen;range=/16;pad_to=3"
    - ";ReRanger;client_port_range;key=low;range=/2048;pad_to=5"
    - ";ReRanger;edns_bufsiz,priming_queries;key=low;range=/512;pad_to=5;allow_invalid_keys=1"
    - ";ReRanger;priming_responses;key=low;range=/128;pad_to=4"
    - ";NetRemap;client_subnet,client_subnet2,client_addr_vs_rcode,ipv6_rsn_abusers;net=8"
  # Generators
  generators:
    - ";client_subnet_country;*"
    - ";client_subnet_authority;fetch=yes"

maxmind_api_key: 